#!/usr/bin/env python3

import hashlib
import sys
from colorama import Fore, Style

# Kode warna
r = Fore.LIGHTRED_EX
g = Fore.LIGHTGREEN_EX
c = Fore.LIGHTCYAN_EX
p = Fore.RESET
w = Fore.LIGHTWHITE_EX
y = Fore.LIGHTYELLOW_EX
b = Fore.LIGHTBLUE_EX

# Algoritma hash yang didukung
algoritma_hash = {
    "1": ("md5", hashlib.md5),
    "2": ("sha1", hashlib.sha1),
    "3": ("sha256", hashlib.sha256),
    "4": ("sha512", hashlib.sha512)
}

print(f"""{c}
       _______
     _/       \_
    / |       | \
   /  |__   __|  \
  |__/((o| |o))\__|
  |      | |      |
  |\     |_|     /|
  | \           / |
   \| /  ___  \ |/
    \ | / _ \ | /
     \_________/
      _|_____|_
 ____|_________|____
/                   \
-------------------------------------------------

             Pemecah Password Hash
               Dibuat oleh FII14

=================================================
{p}""")

print(f"{g}Algoritma hash yang didukung{w}:")
print("==========================")
for i, (algoritma, _) in algoritma_hash.items():
    print(f"[{y}{i}{w}] {algoritma}")
print(f"[{r}Q{w}] Keluar")

pilihan = input(f"\n[{b}#{w}] Masukkan nomor algoritma hash (1-4) atau 'Q' untuk keluar: ").strip()

if pilihan.upper() == 'Q':
    print(f"\n[{g}+{w}] Keluar dari program.")
    sys.exit(0)

try:
    algoritma, fungsi_hash = algoritma_hash[pilihan]
except KeyError:
    print(f"\n[{r}-{w}] Masukan tidak valid.")
    sys.exit(1)

hash_target = input(f"[{b}#{w}] Masukkan hash target: ").strip()
if len(hash_target) == 0:
    print(f"\n[{r}-{w}] Hash tidak valid.")
    sys.exit(1)

file_wordlist = input(f"[{b}#{w}] Masukkan path ke file wordlist: ").strip()
print(f"\n{w}[{y}*{w}] Menghitung jumlah password '{file_wordlist}{p}'")

try:
    jumlah_seluruh_password = 0
    with open(file_wordlist, 'r', encoding='latin-1') as f:
        seluruh_password = f.readlines()
        jumlah_seluruh_password = len(seluruh_password)
        print(f"{w}[{g}+{w}] Jumlah password '{file_wordlist}': '{jumlah_seluruh_password}'{p}")

    print()
    password_ditemukan = False
    jumlah_password_dicoba = 0
    for password in seluruh_password:
        jumlah_password_dicoba += 1
        password = password.strip()
        password_hash = fungsi_hash(password.encode()).hexdigest()
        if password_hash == hash_target:
            password_ditemukan = True
            print(f"{c}================================================={p}")
            print(f"[{g}+{w}] Password ditemukan: '{password}'")
            print(f"{w}[{g}+{p}] Jumlah password yang dicoba: '{jumlah_password_dicoba}'{p}")
            print(f"{c}-------------------------------------------------{p}")

            break
        else:
            print(f"[{r}-{w}] Password salah '{password}'")
    if not password_ditemukan:
        print(f"{c}================================================={p}")
        print(f"\n[{r}-{w}] Password tidak ditemukan dalam wordlist.")
        print(f"{w}[{r}-{p}] Jumlah password yang dicoba: '{jumlah_password_dicoba}'{p}")
        print(f"{c}-------------------------------------------------{p}")

except FileNotFoundError:
    print(f"\n[{r}-{w}] File wordlist tidak ditemukan.")
    sys.exit(1)
except IOError:
    print(f"\n[{r}-{w}] Kesalahan saat membaca file wordlist.")
    sys.exit(1)
