#!/usr/bin/env python
import hashlib

def login():
    while True:
        token = input("Masukkan token: ")

        if verify_token(token):
            hashbrute
            break
        else:
            print("Token tidak valid. Silakan coba lagi.")

def verify_token(token):
    token_valid = "7ab2566e97172e61115282374329351b"
    token_encrypted = hashlib.md5(token.encode()).hexdigest()

    return token_encrypted == token_valid

login()
